# Параметры системы
WIDTH = 1200
HEIGHT = 600
FPS = 20

# Изначальные параметры
INITIAL_FOOD = 400
INITIAL_CELLS = 10

FOOD_RESPAWN_DELAY = 2*FPS

# Параметры клеток
MUTATION_PROBABILITY = 400
DUPLICATION_PERIOD = 4*FPS

ERA_PERIOD = 100
